[general]
import = [
    "~/.config/alacritty/themes/noctalia.toml"
]

# Настройки оконного менеджера Alacritty

[window]
# Размеры внутренних отступов (чтобы текст не прилипал к краям экрана)
padding = { x = 1, y =  }
opacity = 0.90

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"


[cursor]
style = { shape = "Beam", blinking = "On" }

# Отключаем прозрачность окна (как советует автор, чтобы не портить читаемость текста)
#opacity = 0.8

[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"


# Включаем встроенную отрисовку символов (рамок, линий) для бесшовного интерфейса

