[colors.primary]
background = '#292414'
foreground = '#f3f3f2'

[colors.cursor]
text = '#292414'
cursor = '#f3f3f2'

[colors.vi_mode_cursor]
text = '#292414'
cursor = '#f8cb54'

[colors.search.matches]
foreground = '#372f1b'
background = '#6ff63c'

[colors.search.focused_match]
foreground = '#372f1b'
background = '#f8cb54'

[colors.footer_bar]
foreground = '#372f1b'
background = '#e8e6e3'

[colors.hints.start]
foreground = '#372f1b'
background = '#cdf63c'

[colors.hints.end]
foreground = '#372f1b'
background = '#cdf63c'

[colors.selection]
text = '#b6b4af'
background = '#372f1b'


[colors.normal]
black   = '#372f1b'
red     = '#fd4663'
green   = '#f8cb54'
yellow  = '#cdf63c'
blue    = '#6ff63c'
magenta = '#fada85'
cyan    = '#e0f985'
white   = '#f3f3f2'


[colors.bright]
black   = '#726d62'
red     = '#fd4663'
green   = '#f8cb54'
yellow  = '#cdf63c'
blue    = '#6ff63c'
magenta = '#fada85'
cyan    = '#e0f985'
white   = '#f3f3f2'


[colors.dim]
black   = '#372f1b'
red     = '#fd4663'
green   = '#f8cb54'
yellow  = '#cdf63c'
blue    = '#6ff63c'
magenta = '#fada85'
cyan    = '#e0f985'
white   = '#f3f3f2'
